#!/bin/sh
set -eu

cat > /app/public/env-config.js <<EOF
window.__PUBLIC_ENV__ = {
  NEXT_PUBLIC_API_BASE_URL: "${NEXT_PUBLIC_API_BASE_URL:-}",
  NEXT_PUBLIC_APPWRITE_ENDPOINT: "${NEXT_PUBLIC_APPWRITE_ENDPOINT:-}",
  NEXT_PUBLIC_APPWRITE_PROJECT_ID: "${NEXT_PUBLIC_APPWRITE_PROJECT_ID:-}",
  NEXT_PUBLIC_APPWRITE_PRODUCT_IMAGES_BUCKET_ID: "${NEXT_PUBLIC_APPWRITE_PRODUCT_IMAGES_BUCKET_ID:-}",
  NEXT_PUBLIC_APPWRITE_BUSINESS_ASSETS_BUCKET_ID: "${NEXT_PUBLIC_APPWRITE_BUSINESS_ASSETS_BUCKET_ID:-}",
  NEXT_PUBLIC_APPWRITE_USER_AVATARS_BUCKET_ID: "${NEXT_PUBLIC_APPWRITE_USER_AVATARS_BUCKET_ID:-}",
  NEXT_PUBLIC_APPWRITE_DOCUMENTS_BUCKET_ID: "${NEXT_PUBLIC_APPWRITE_DOCUMENTS_BUCKET_ID:-}"
};
EOF

exec "$@"
