export const PERMISSION_KEYS = [
  "accounting.view",
  "accounting.accounts.manage",
  "accounting.journal_entries.manage",
  "users.view",
  "users.create",
  "users.edit",
  "users.delete",
  "users.status.update",
  "users.invite",
  "users.invitation.resend",
  "users.invitation.cancel",
  "users.activity.view",
  "roles.view",
  "roles.create",
  "roles.edit",
  "roles.delete",
  "roles.permissions.view",
  "roles.permissions.update",
  "branches.view",
  "branches.create",
  "branches.edit",
  "branches.status.update",
  "branches.switch",
  "branches.access.manage",
  "settings.view",
  "settings.company.update",
  "settings.tax_rates.manage",
  "settings.payment_methods.manage",
  "settings.receipt.update",
  "settings.hardware.update",
  "settings.notifications.update",
  "master_data.view",
  "master_data.units.manage",
  "master_data.product_categories.manage",
  "master_data.ingredient_categories.manage",
  "master_data.packaging_categories.manage",
  "master_data.order_statuses.manage",
  "master_data.payment_statuses.manage",
  "pos.view",
  "pos.sell",
  "pos.checkout",
  "pos.discount.apply",
  "pos.hold_sale",
  "pos.resume_sale",
  "pos.cancel_held_sale",
  "pos.refund",
  "pos.void",
  "payments.view",
  "payments.add",
  "payments.refund",
  "payments.reconcile",
  "payments.summary.view",
  "payments.methods.view",
  "expenses.view",
  "expenses.create",
  "expenses.edit",
  "expenses.delete",
  "expenses.manage",
  "products.view",
  "products.create",
  "products.edit",
  "products.delete",
  "products.status.update",
  "products.variants.manage",
  "products.images.manage",
  "recipes.view",
  "recipes.create",
  "recipes.edit",
  "recipes.delete",
  "recipes.status.update",
  "recipes.ingredients.manage",
  "recipes.packaging.manage",
  "recipes.cost.recalculate",
  "recipes.versions.create",
  "manufacturing.view",
  "manufacturing.batches.create",
  "manufacturing.batches.edit",
  "manufacturing.batches.delete",
  "manufacturing.batches.start",
  "manufacturing.batches.consume",
  "manufacturing.batches.produce",
  "manufacturing.batches.wastage",
  "manufacturing.batches.complete",
  "manufacturing.batches.cancel",
  "purchasing.view",
  "purchasing.orders.create",
  "purchasing.orders.edit",
  "purchasing.orders.delete",
  "purchasing.orders.status.update",
  "purchasing.invoices.create",
  "purchasing.invoices.edit",
  "purchasing.invoices.post",
  "purchasing.invoices.cancel",
  "purchasing.receipts.create",
  "purchasing.receipts.post",
  "purchasing.receipts.cancel",
  "purchasing.receive_stock",
  "customers.view",
  "customers.create",
  "customers.edit",
  "customers.delete",
  "customers.status.update",
  "customers.notes.manage",
  "customers.tags.manage",
  "customers.quick_create",
  "suppliers.view",
  "suppliers.create",
  "suppliers.edit",
  "suppliers.delete",
  "suppliers.status.update",
  "suppliers.contacts.manage",
  "suppliers.notes.manage",
  "suppliers.lookup",
  "orders.view",
  "orders.create",
  "orders.edit",
  "orders.delete",
  "orders.status.update",
  "orders.payments.manage",
  "orders.production.assign",
  "orders.packaging.manage",
  "inventory.view",
  "inventory.opening_stock",
  "inventory.adjust",
  "inventory.locations.manage",
  "inventory.transfer.create",
  "inventory.transfer.complete",
  "inventory.transfer.cancel",
  "inventory.movements.view",
  "inventory.low_stock.view",
  "inventory.expiry.view",
  "inventory.expiry_batches.manage",
  "stock_movements.view",
  "stock_movements.manual_create",
  "stock_movements.reverse",
  "stock_movements.audit.view",
  "stock_movements.summary.view",
  "ingredients.view",
  "ingredients.create",
  "ingredients.edit",
  "ingredients.delete",
  "ingredients.status.update",
  "packaging.view",
  "packaging.create",
  "packaging.edit",
  "packaging.delete",
  "packaging.status.update",
  "packaging.usage_rules.manage",
  "reports.view",
  "reports.sales.view",
  "reports.inventory.view",
  "reports.payments.view",
  "reports.production.view",
  "reports.export",
  "audit_logs.view",
] as const;

export const PERMISSION_MODULES = [
  "accounting",
  "users",
  "roles",
  "branches",
  "settings",
  "master_data",
  "pos",
  "payments",
  "expenses",
  "products",
  "recipes",
  "manufacturing",
  "purchasing",
  "customers",
  "suppliers",
  "orders",
  "inventory",
  "stock_movements",
  "ingredients",
  "packaging",
  "reports",
  "audit_logs",
] as const;

export type KnownPermission = (typeof PERMISSION_KEYS)[number];
export type KnownPermissionModuleName = (typeof PERMISSION_MODULES)[number];
export type Permission = KnownPermission | (string & {});
export type PermissionModuleName = KnownPermissionModuleName | (string & {});

export type PermissionDefinition = {
  id: string;
  moduleName: PermissionModuleName;
  permissionKey: Permission;
  description: string;
  createdAt: string;
  updatedAt: string;
};

export type RolePermission = {
  roleId: string;
  permissionId: string;
  allowed: boolean;
};

export const PERMISSION_MODULE_META: Record<
  KnownPermissionModuleName,
  {
    title: string;
    description: string;
  }
> = {
  accounting: {
    title: "Accounting",
    description: "Control Chart of Accounts access and future accounting workflows.",
  },
  users: {
    title: "Users",
    description: "Control staff account visibility, creation, editing, and removal.",
  },
  roles: {
    title: "Roles",
    description: "Manage access templates and permission assignments across the platform.",
  },
  branches: {
    title: "Branches",
    description: "Control branch visibility, setup, and location-level administration.",
  },
  settings: {
    title: "Settings",
    description: "Grant access to company configuration, business setup, and administration.",
  },
  master_data: {
    title: "Master Data",
    description: "Manage reference data used throughout pastry, retail, and production flows.",
  },
  pos: {
    title: "POS",
    description: "Control selling, counter workflows, and refund operations in the register.",
  },
  payments: {
    title: "Payments",
    description: "Control payment tracking, refunds, collection summaries, and reconciliation.",
  },
  expenses: {
    title: "Expenses",
    description: "Record business expenses and control supplier/customer expense tagging.",
  },
  products: {
    title: "Products",
    description: "View and maintain the pastry catalog, pricing, and product structure.",
  },
  recipes: {
    title: "Recipes",
    description: "Control BOM recipes, ingredient lines, packaging lines, yield, and costing.",
  },
  manufacturing: {
    title: "Manufacturing",
    description: "Control production batches, ingredient consumption, output, and wastage.",
  },
  purchasing: {
    title: "Purchasing",
    description: "Control supplier purchasing, invoices, receipts, and stock receiving.",
  },
  customers: {
    title: "Customers",
    description: "Manage customer profiles, notes, tags, and POS customer lookup access.",
  },
  suppliers: {
    title: "Suppliers",
    description: "Manage supplier profiles, procurement contacts, notes, and lookup access.",
  },
  orders: {
    title: "Orders",
    description: "Allow order visibility and operational control over order handling.",
  },
  inventory: {
    title: "Inventory",
    description: "Control stock visibility and inventory adjustment capabilities.",
  },
  reports: {
    title: "Reports",
    description: "Grant access to reporting and business performance visibility.",
  },
  stock_movements: {
    title: "Stock Movements",
    description: "Control stock ledger visibility, manual movements, reversals, and audits.",
  },
  ingredients: {
    title: "Ingredients",
    description: "Manage ingredient catalog access and ingredient status changes.",
  },
  packaging: {
    title: "Packaging",
    description: "Manage packaging catalog access, status changes, and usage rules.",
  },
  audit_logs: {
    title: "Audit Logs",
    description: "Control audit trail visibility across sensitive system actions.",
  },
};
