WITH permission_seed(module_name, permission_key) AS (
  VALUES
    ('users', 'users.view'),
    ('users', 'users.create'),
    ('users', 'users.edit'),
    ('users', 'users.delete'),
    ('users', 'users.status.update'),
    ('users', 'users.invite'),
    ('users', 'users.invitation.resend'),
    ('users', 'users.invitation.cancel'),
    ('users', 'users.activity.view'),
    ('roles', 'roles.view'),
    ('roles', 'roles.create'),
    ('roles', 'roles.edit'),
    ('roles', 'roles.delete'),
    ('roles', 'roles.permissions.view'),
    ('roles', 'roles.permissions.update'),
    ('branches', 'branches.view'),
    ('branches', 'branches.create'),
    ('branches', 'branches.edit'),
    ('branches', 'branches.status.update'),
    ('branches', 'branches.switch'),
    ('branches', 'branches.access.manage'),
    ('settings', 'settings.view'),
    ('settings', 'settings.company.update'),
    ('settings', 'settings.tax_rates.manage'),
    ('settings', 'settings.payment_methods.manage'),
    ('settings', 'settings.receipt.update'),
    ('settings', 'settings.hardware.update'),
    ('settings', 'settings.notifications.update'),
    ('master_data', 'master_data.view'),
    ('master_data', 'master_data.units.manage'),
    ('master_data', 'master_data.product_categories.manage'),
    ('master_data', 'master_data.ingredient_categories.manage'),
    ('master_data', 'master_data.packaging_categories.manage'),
    ('master_data', 'master_data.supplier_categories.manage'),
    ('master_data', 'master_data.order_statuses.manage'),
    ('master_data', 'master_data.payment_statuses.manage'),
    ('products', 'products.view'),
    ('products', 'products.create'),
    ('products', 'products.edit'),
    ('products', 'products.delete'),
    ('products', 'products.status.update'),
    ('products', 'products.variants.manage'),
    ('products', 'products.images.manage'),
    ('pos', 'pos.view'),
    ('pos', 'pos.sell'),
    ('pos', 'pos.checkout'),
    ('pos', 'pos.discount.apply'),
    ('pos', 'pos.hold_sale'),
    ('pos', 'pos.resume_sale'),
    ('pos', 'pos.cancel_held_sale'),
    ('pos', 'pos.refund'),
    ('pos', 'pos.void'),
    ('payments', 'payments.view'),
    ('payments', 'payments.add'),
    ('payments', 'payments.refund'),
    ('payments', 'payments.reconcile'),
    ('payments', 'payments.summary.view'),
    ('payments', 'payments.methods.view'),
    ('customers', 'customers.view'),
    ('customers', 'customers.create'),
    ('customers', 'customers.edit'),
    ('customers', 'customers.delete'),
    ('customers', 'customers.status.update'),
    ('customers', 'customers.notes.manage'),
    ('customers', 'customers.tags.manage'),
    ('customers', 'customers.quick_create'),
    ('orders', 'orders.view'),
    ('orders', 'orders.create'),
    ('orders', 'orders.edit'),
    ('orders', 'orders.delete'),
    ('orders', 'orders.status.update'),
    ('orders', 'orders.payments.manage'),
    ('orders', 'orders.production.assign'),
    ('orders', 'orders.packaging.manage'),
    ('inventory', 'inventory.view'),
    ('inventory', 'inventory.opening_stock'),
    ('inventory', 'inventory.adjust'),
    ('inventory', 'inventory.movements.view'),
    ('inventory', 'inventory.low_stock.view'),
    ('inventory', 'inventory.expiry.view'),
    ('inventory', 'inventory.expiry_batches.manage'),
    ('stock_movements', 'stock_movements.view'),
    ('stock_movements', 'stock_movements.manual_create'),
    ('stock_movements', 'stock_movements.reverse'),
    ('stock_movements', 'stock_movements.audit.view'),
    ('stock_movements', 'stock_movements.summary.view'),
    ('ingredients', 'ingredients.view'),
    ('ingredients', 'ingredients.create'),
    ('ingredients', 'ingredients.edit'),
    ('ingredients', 'ingredients.delete'),
    ('ingredients', 'ingredients.status.update'),
    ('suppliers', 'suppliers.view'),
    ('suppliers', 'suppliers.create'),
    ('suppliers', 'suppliers.edit'),
    ('suppliers', 'suppliers.delete'),
    ('suppliers', 'suppliers.status.update'),
    ('suppliers', 'suppliers.contacts.manage'),
    ('suppliers', 'suppliers.notes.manage'),
    ('suppliers', 'suppliers.lookup'),
    ('purchasing', 'purchasing.view'),
    ('purchasing', 'purchasing.orders.create'),
    ('purchasing', 'purchasing.orders.edit'),
    ('purchasing', 'purchasing.orders.delete'),
    ('purchasing', 'purchasing.orders.status.update'),
    ('purchasing', 'purchasing.invoices.create'),
    ('purchasing', 'purchasing.invoices.edit'),
    ('purchasing', 'purchasing.invoices.post'),
    ('purchasing', 'purchasing.invoices.cancel'),
    ('purchasing', 'purchasing.receipts.create'),
    ('purchasing', 'purchasing.receipts.post'),
    ('purchasing', 'purchasing.receipts.cancel'),
    ('purchasing', 'purchasing.receive_stock'),
    ('packaging', 'packaging.view'),
    ('packaging', 'packaging.create'),
    ('packaging', 'packaging.edit'),
    ('packaging', 'packaging.delete'),
    ('packaging', 'packaging.status.update'),
    ('packaging', 'packaging.usage_rules.manage'),
    ('recipes', 'recipes.view'),
    ('recipes', 'recipes.create'),
    ('recipes', 'recipes.edit'),
    ('recipes', 'recipes.delete'),
    ('recipes', 'recipes.status.update'),
    ('recipes', 'recipes.ingredients.manage'),
    ('recipes', 'recipes.packaging.manage'),
    ('recipes', 'recipes.cost.recalculate'),
    ('recipes', 'recipes.versions.create'),
    ('manufacturing', 'manufacturing.view'),
    ('manufacturing', 'manufacturing.batches.create'),
    ('manufacturing', 'manufacturing.batches.edit'),
    ('manufacturing', 'manufacturing.batches.delete'),
    ('manufacturing', 'manufacturing.batches.start'),
    ('manufacturing', 'manufacturing.batches.consume'),
    ('manufacturing', 'manufacturing.batches.produce'),
    ('manufacturing', 'manufacturing.batches.wastage'),
    ('manufacturing', 'manufacturing.batches.complete'),
    ('manufacturing', 'manufacturing.batches.cancel'),
    ('reports', 'reports.view'),
    ('reports', 'reports.sales.view'),
    ('reports', 'reports.inventory.view'),
    ('reports', 'reports.payments.view'),
    ('reports', 'reports.production.view'),
    ('reports', 'reports.export'),
    ('audit_logs', 'audit_logs.view')
)
INSERT INTO permissions (id, module_name, permission_key, description, created_at, updated_at)
SELECT gen_random_uuid(), module_name, permission_key, initcap(replace(permission_key, '.', ' ')), now(), now()
FROM permission_seed
ON CONFLICT (permission_key) DO UPDATE
SET module_name = EXCLUDED.module_name,
    updated_at = now();

INSERT INTO role_permissions (id, role_id, permission_id, allowed, created_at, updated_at)
SELECT gen_random_uuid(), r.id, p.id, true, now(), now()
FROM roles r
CROSS JOIN permissions p
WHERE r.business_id IS NOT NULL
  AND r.role_name = 'Admin'
  AND r.deleted_at IS NULL
  AND NOT EXISTS (
    SELECT 1
    FROM role_permissions rp
    WHERE rp.role_id = r.id
      AND rp.permission_id = p.id
  );

WITH role_permission_seed(role_name, permission_key) AS (
  VALUES
    ('Cashier', 'products.view'),
    ('Cashier', 'customers.view'),
    ('Cashier', 'customers.create'),
    ('Cashier', 'customers.quick_create'),
    ('Cashier', 'orders.view'),
    ('Cashier', 'orders.create'),
    ('Cashier', 'orders.payments.manage'),
    ('Cashier', 'pos.view'),
    ('Cashier', 'pos.sell'),
    ('Cashier', 'pos.checkout'),
    ('Cashier', 'pos.discount.apply'),
    ('Cashier', 'pos.hold_sale'),
    ('Cashier', 'pos.resume_sale'),
    ('Cashier', 'pos.cancel_held_sale'),
    ('Cashier', 'payments.view'),
    ('Cashier', 'payments.add'),
    ('Cashier', 'payments.methods.view'),
    ('Manager', 'users.view'),
    ('Manager', 'users.create'),
    ('Manager', 'users.edit'),
    ('Manager', 'users.status.update'),
    ('Manager', 'users.invite'),
    ('Manager', 'users.invitation.resend'),
    ('Manager', 'users.invitation.cancel'),
    ('Manager', 'users.activity.view'),
    ('Manager', 'roles.view'),
    ('Manager', 'roles.create'),
    ('Manager', 'roles.edit'),
    ('Manager', 'roles.delete'),
    ('Manager', 'roles.permissions.view'),
    ('Manager', 'roles.permissions.update'),
    ('Manager', 'branches.view'),
    ('Manager', 'branches.create'),
    ('Manager', 'branches.edit'),
    ('Manager', 'branches.status.update'),
    ('Manager', 'branches.switch'),
    ('Manager', 'branches.access.manage'),
    ('Manager', 'settings.view'),
    ('Manager', 'settings.company.update'),
    ('Manager', 'settings.tax_rates.manage'),
    ('Manager', 'settings.payment_methods.manage'),
    ('Manager', 'settings.receipt.update'),
    ('Manager', 'master_data.view'),
    ('Manager', 'master_data.units.manage'),
    ('Manager', 'master_data.product_categories.manage'),
    ('Manager', 'master_data.ingredient_categories.manage'),
    ('Manager', 'master_data.packaging_categories.manage'),
    ('Manager', 'master_data.supplier_categories.manage'),
    ('Manager', 'master_data.order_statuses.manage'),
    ('Manager', 'master_data.payment_statuses.manage'),
    ('Manager', 'pos.view'),
    ('Manager', 'pos.sell'),
    ('Manager', 'pos.checkout'),
    ('Manager', 'pos.discount.apply'),
    ('Manager', 'pos.hold_sale'),
    ('Manager', 'pos.resume_sale'),
    ('Manager', 'pos.cancel_held_sale'),
    ('Manager', 'pos.refund'),
    ('Manager', 'pos.void'),
    ('Manager', 'products.view'),
    ('Manager', 'products.create'),
    ('Manager', 'products.edit'),
    ('Manager', 'products.delete'),
    ('Manager', 'products.status.update'),
    ('Manager', 'products.variants.manage'),
    ('Manager', 'products.images.manage'),
    ('Manager', 'customers.view'),
    ('Manager', 'customers.create'),
    ('Manager', 'customers.edit'),
    ('Manager', 'customers.delete'),
    ('Manager', 'customers.status.update'),
    ('Manager', 'customers.notes.manage'),
    ('Manager', 'customers.tags.manage'),
    ('Manager', 'customers.quick_create'),
    ('Manager', 'orders.view'),
    ('Manager', 'orders.create'),
    ('Manager', 'orders.edit'),
    ('Manager', 'orders.delete'),
    ('Manager', 'orders.status.update'),
    ('Manager', 'orders.payments.manage'),
    ('Manager', 'orders.production.assign'),
    ('Manager', 'orders.packaging.manage'),
    ('Manager', 'inventory.view'),
    ('Manager', 'inventory.opening_stock'),
    ('Manager', 'inventory.adjust'),
    ('Manager', 'inventory.movements.view'),
    ('Manager', 'inventory.low_stock.view'),
    ('Manager', 'inventory.expiry.view'),
    ('Manager', 'inventory.expiry_batches.manage'),
    ('Manager', 'stock_movements.view'),
    ('Manager', 'stock_movements.manual_create'),
    ('Manager', 'stock_movements.reverse'),
    ('Manager', 'stock_movements.audit.view'),
    ('Manager', 'stock_movements.summary.view'),
    ('Manager', 'ingredients.view'),
    ('Manager', 'ingredients.create'),
    ('Manager', 'ingredients.edit'),
    ('Manager', 'ingredients.delete'),
    ('Manager', 'ingredients.status.update'),
    ('Manager', 'suppliers.view'),
    ('Manager', 'suppliers.create'),
    ('Manager', 'suppliers.edit'),
    ('Manager', 'suppliers.delete'),
    ('Manager', 'suppliers.status.update'),
    ('Manager', 'suppliers.contacts.manage'),
    ('Manager', 'suppliers.notes.manage'),
    ('Manager', 'suppliers.lookup'),
    ('Manager', 'purchasing.view'),
    ('Manager', 'purchasing.orders.create'),
    ('Manager', 'purchasing.orders.edit'),
    ('Manager', 'purchasing.orders.delete'),
    ('Manager', 'purchasing.orders.status.update'),
    ('Manager', 'purchasing.invoices.create'),
    ('Manager', 'purchasing.invoices.edit'),
    ('Manager', 'purchasing.invoices.post'),
    ('Manager', 'purchasing.invoices.cancel'),
    ('Manager', 'purchasing.receipts.create'),
    ('Manager', 'purchasing.receipts.post'),
    ('Manager', 'purchasing.receipts.cancel'),
    ('Manager', 'purchasing.receive_stock'),
    ('Manager', 'packaging.view'),
    ('Manager', 'packaging.create'),
    ('Manager', 'packaging.edit'),
    ('Manager', 'packaging.delete'),
    ('Manager', 'packaging.status.update'),
    ('Manager', 'packaging.usage_rules.manage'),
    ('Manager', 'recipes.view'),
    ('Manager', 'recipes.create'),
    ('Manager', 'recipes.edit'),
    ('Manager', 'recipes.delete'),
    ('Manager', 'recipes.status.update'),
    ('Manager', 'recipes.ingredients.manage'),
    ('Manager', 'recipes.packaging.manage'),
    ('Manager', 'recipes.cost.recalculate'),
    ('Manager', 'recipes.versions.create'),
    ('Manager', 'manufacturing.view'),
    ('Manager', 'manufacturing.batches.create'),
    ('Manager', 'manufacturing.batches.edit'),
    ('Manager', 'manufacturing.batches.start'),
    ('Manager', 'manufacturing.batches.consume'),
    ('Manager', 'manufacturing.batches.produce'),
    ('Manager', 'manufacturing.batches.wastage'),
    ('Manager', 'manufacturing.batches.complete'),
    ('Manager', 'manufacturing.batches.cancel'),
    ('Manager', 'reports.view'),
    ('Manager', 'reports.sales.view'),
    ('Manager', 'reports.inventory.view'),
    ('Manager', 'reports.payments.view'),
    ('Manager', 'reports.production.view'),
    ('Manager', 'audit_logs.view'),
    ('Inventory Clerk', 'master_data.view'),
    ('Inventory Clerk', 'branches.view'),
    ('Inventory Clerk', 'products.view'),
    ('Inventory Clerk', 'products.create'),
    ('Inventory Clerk', 'products.edit'),
    ('Inventory Clerk', 'products.status.update'),
    ('Inventory Clerk', 'products.variants.manage'),
    ('Inventory Clerk', 'inventory.view'),
    ('Inventory Clerk', 'inventory.opening_stock'),
    ('Inventory Clerk', 'inventory.adjust'),
    ('Inventory Clerk', 'inventory.movements.view'),
    ('Inventory Clerk', 'inventory.low_stock.view'),
    ('Inventory Clerk', 'inventory.expiry.view'),
    ('Inventory Clerk', 'inventory.expiry_batches.manage'),
    ('Inventory Clerk', 'stock_movements.view'),
    ('Inventory Clerk', 'stock_movements.manual_create'),
    ('Inventory Clerk', 'stock_movements.reverse'),
    ('Inventory Clerk', 'stock_movements.audit.view'),
    ('Inventory Clerk', 'stock_movements.summary.view'),
    ('Inventory Clerk', 'ingredients.view'),
    ('Inventory Clerk', 'ingredients.create'),
    ('Inventory Clerk', 'ingredients.edit'),
    ('Inventory Clerk', 'ingredients.status.update'),
    ('Inventory Clerk', 'suppliers.view'),
    ('Inventory Clerk', 'suppliers.create'),
    ('Inventory Clerk', 'suppliers.edit'),
    ('Inventory Clerk', 'suppliers.lookup'),
    ('Inventory Clerk', 'purchasing.view'),
    ('Inventory Clerk', 'purchasing.orders.create'),
    ('Inventory Clerk', 'purchasing.orders.edit'),
    ('Inventory Clerk', 'purchasing.invoices.create'),
    ('Inventory Clerk', 'purchasing.invoices.edit'),
    ('Inventory Clerk', 'purchasing.receipts.create'),
    ('Inventory Clerk', 'purchasing.receipts.post'),
    ('Inventory Clerk', 'purchasing.receive_stock'),
    ('Inventory Clerk', 'packaging.view'),
    ('Inventory Clerk', 'packaging.create'),
    ('Inventory Clerk', 'packaging.edit'),
    ('Inventory Clerk', 'packaging.status.update'),
    ('Inventory Clerk', 'recipes.view'),
    ('Inventory Clerk', 'recipes.create'),
    ('Inventory Clerk', 'recipes.edit'),
    ('Inventory Clerk', 'recipes.ingredients.manage'),
    ('Inventory Clerk', 'recipes.packaging.manage'),
    ('Inventory Clerk', 'recipes.cost.recalculate'),
    ('Inventory Clerk', 'manufacturing.view'),
    ('Inventory Clerk', 'manufacturing.batches.create'),
    ('Inventory Clerk', 'manufacturing.batches.edit'),
    ('Inventory Clerk', 'manufacturing.batches.start'),
    ('Inventory Clerk', 'manufacturing.batches.consume'),
    ('Inventory Clerk', 'manufacturing.batches.complete'),
    ('Inventory Clerk', 'orders.view')
)
INSERT INTO role_permissions (id, role_id, permission_id, allowed, created_at, updated_at)
SELECT gen_random_uuid(), r.id, p.id, true, now(), now()
FROM role_permission_seed seed
JOIN roles r ON r.role_name = seed.role_name
JOIN permissions p ON p.permission_key = seed.permission_key
WHERE r.business_id IS NOT NULL
  AND r.deleted_at IS NULL
  AND NOT EXISTS (
    SELECT 1
    FROM role_permissions rp
    WHERE rp.role_id = r.id
      AND rp.permission_id = p.id
  );
