import { PERMISSIONS } from "@/constants/permissions";
import type { SettingsSection } from "@/types/settings";

export const SETTINGS_SECTIONS: SettingsSection[] = [
  {
    id: "company-profile",
    title: "Company Profile",
    description:
      "Manage business name, logo, address, VAT/TRN, currency, timezone, and contact details.",
    iconName: "Building2",
    permission: PERMISSIONS.settingsView,
    managePermission: PERMISSIONS.settingsCompanyUpdate,
    route: "/settings/company-profile",
    status: "available",
    category: "system",
    actionLabel: "Configure",
  },
  {
    id: "branch-management",
    title: "Branch Management",
    description: "Manage locations, branch details, branch users, and branch-level operations.",
    iconName: "Store",
    permission: PERMISSIONS.settingsView,
    managePermission: PERMISSIONS.branchesEdit,
    route: "/settings/branches",
    status: "available",
    category: "system",
    actionLabel: "Configure",
  },
  {
    id: "tax-rates",
    title: "Tax Rates",
    description: "Create VAT, GST, sales tax, service charges, and region-based tax profiles.",
    iconName: "Percent",
    permission: PERMISSIONS.settingsView,
    managePermission: PERMISSIONS.settingsTaxRatesManage,
    route: "/settings/tax-rates",
    status: "available",
    category: "system",
    actionLabel: "Configure",
  },
  {
    id: "payment-methods",
    title: "Payment Methods",
    description:
      "Control cash, card, bank transfer, split payment, and future online payment options.",
    iconName: "CreditCard",
    permission: PERMISSIONS.settingsView,
    managePermission: PERMISSIONS.settingsPaymentMethodsManage,
    route: "/settings/payment-methods",
    status: "available",
    category: "system",
    actionLabel: "Configure",
  },
  {
    id: "receipts",
    title: "Receipt & Invoice Settings",
    description:
      "Customize receipt format, invoice footer, QR code, printer layout, and digital receipt options.",
    iconName: "Receipt",
    permission: PERMISSIONS.settingsView,
    managePermission: PERMISSIONS.settingsReceiptUpdate,
    route: "/settings/receipts",
    status: "available",
    category: "system",
    actionLabel: "Configure",
  },
  {
    id: "hardware",
    title: "Hardware Settings",
    description:
      "Prepare barcode scanner, receipt printer, cash drawer, kitchen printer, and label printer configurations.",
    iconName: "Printer",
    permission: PERMISSIONS.settingsView,
    managePermission: PERMISSIONS.settingsHardwareUpdate,
    route: "/settings/hardware",
    status: "coming_soon",
    category: "system",
    actionLabel: "Configure",
  },
  {
    id: "notifications",
    title: "Notifications",
    description:
      "Configure low-stock alerts, expiry alerts, order reminders, staff notifications, email, and SMS alerts.",
    iconName: "Bell",
    permission: PERMISSIONS.settingsView,
    managePermission: PERMISSIONS.settingsNotificationsUpdate,
    route: "/settings/notifications",
    status: "coming_soon",
    category: "system",
    actionLabel: "Configure",
  },
  {
    id: "subscription",
    title: "Subscription & Billing",
    description:
      "View current plan, user limits, branch limits, billing cycle, and subscription status.",
    iconName: "BadgeDollarSign",
    permission: PERMISSIONS.settingsView,
    managePermission: PERMISSIONS.settingsCompanyUpdate,
    route: "/settings/subscription",
    status: "coming_soon",
    category: "system",
    actionLabel: "View Plan",
  },
  {
    id: "units",
    title: "Units & Measurements",
    description: "Manage kg, g, ml, ltr, pcs, box, tray, cup, and custom unit conversions.",
    iconName: "Scale",
    permission: PERMISSIONS.masterDataView,
    managePermission: PERMISSIONS.masterDataUnitsManage,
    route: "/settings/master-data/units",
    status: "available",
    category: "master_data",
    actionLabel: "Configure",
  },
  {
    id: "product-categories",
    title: "Product Categories",
    description: "Create and organize product categories for POS billing and catalog management.",
    iconName: "Package",
    permission: PERMISSIONS.masterDataView,
    managePermission: PERMISSIONS.masterDataProductCategoriesManage,
    route: "/settings/master-data/product-categories",
    status: "available",
    category: "master_data",
    actionLabel: "Configure",
  },
  {
    id: "ingredient-categories",
    title: "Ingredient Categories",
    description:
      "Group raw materials like flour, sugar, dairy, flavorings, and production ingredients.",
    iconName: "Wheat",
    permission: PERMISSIONS.masterDataView,
    managePermission: PERMISSIONS.masterDataIngredientCategoriesManage,
    route: "/settings/master-data/ingredient-categories",
    status: "available",
    category: "master_data",
    actionLabel: "Configure",
  },
  {
    id: "packaging-categories",
    title: "Packaging Categories",
    description: "Manage boxes, cups, trays, bags, labels, stickers, candles, and packaging types.",
    iconName: "Archive",
    permission: PERMISSIONS.masterDataView,
    managePermission: PERMISSIONS.masterDataPackagingCategoriesManage,
    route: "/settings/master-data/packaging-categories",
    status: "available",
    category: "master_data",
    actionLabel: "Configure",
  },
  {
    id: "supplier-categories",
    title: "Supplier Categories",
    description:
      "Classify ingredient suppliers, packaging suppliers, equipment suppliers, and service providers.",
    iconName: "Truck",
    permission: PERMISSIONS.masterDataView,
    managePermission: PERMISSIONS.masterDataSupplierCategoriesManage,
    route: "/settings/master-data/supplier-categories",
    status: "available",
    category: "master_data",
    actionLabel: "Configure",
  },
  {
    id: "order-statuses",
    title: "Order Statuses",
    description:
      "Define order workflow statuses such as New, Confirmed, In Production, Ready, Delivered, and Completed.",
    iconName: "ListChecks",
    permission: PERMISSIONS.masterDataView,
    managePermission: PERMISSIONS.masterDataOrderStatusesManage,
    route: "/settings/master-data/order-statuses",
    status: "available",
    category: "master_data",
    actionLabel: "Configure",
  },
  {
    id: "payment-statuses",
    title: "Payment Statuses",
    description: "Manage payment statuses such as Pending, Partial, Paid, Refunded, and Overdue.",
    iconName: "WalletCards",
    permission: PERMISSIONS.masterDataView,
    managePermission: PERMISSIONS.masterDataPaymentStatusesManage,
    route: "/settings/master-data/payment-statuses",
    status: "available",
    category: "master_data",
    actionLabel: "Configure",
  },
  {
    id: "loyalty",
    title: "Coupon & Loyalty Rules",
    description: "Prepare promotion types, coupon rules, loyalty points, and reward configuration.",
    iconName: "Gift",
    permission: PERMISSIONS.masterDataView,
    managePermission: PERMISSIONS.masterDataOrderStatusesManage,
    route: "/settings/master-data/loyalty",
    status: "coming_soon",
    category: "master_data",
    actionLabel: "Configure",
  },
];
